# Generated by Django 5.2.3 on 2025-07-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlaystylePicker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueChamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('url', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='leagueitem',
            name='url',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leagueitem',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
