# Generated by Django 5.2.3 on 2025-07-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlaystylePicker', '0003_alter_leagueitem_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leagueitem',
            name='url',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
