# Generated by Django 5.2.3 on 2025-07-10 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlaystylePicker', '0004_alter_leagueitem_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueRune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('url', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
