# Generated by Django 5.2.3 on 2025-07-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlaystylePicker', '0005_leaguerune'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopBuilds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champion', models.CharField(max_length=100)),
                ('items', models.JSONField()),
                ('runes', models.JSONField()),
                ('ability_order', models.JSONField()),
            ],
        ),
    ]
