# Generated by Django 5.2.3 on 2025-07-17 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlaystylePicker', '0006_topbuilds'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotBuilds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champion', models.CharField(max_length=100)),
                ('items', models.JSONField()),
                ('runes', models.JSONField()),
                ('ability_order', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='JungleBuilds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champion', models.CharField(max_length=100)),
                ('items', models.JSONField()),
                ('runes', models.JSONField()),
                ('ability_order', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='MidBuilds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champion', models.CharField(max_length=100)),
                ('items', models.JSONField()),
                ('runes', models.JSONField()),
                ('ability_order', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='SupportBuilds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champion', models.CharField(max_length=100)),
                ('items', models.JSONField()),
                ('runes', models.JSONField()),
                ('ability_order', models.JSONField()),
            ],
        ),
    ]
